package com.ts.common.ui.pages.portlets;

import com.codeborne.selenide.Condition;
import com.codeborne.selenide.ElementsCollection;
import com.codeborne.selenide.SelenideElement;
import com.ts.common.asserts.UiAsserts;
import com.ts.common.ui.pages.BasePage;
import lombok.Getter;

import static com.codeborne.selenide.Selenide.$$x;
import static com.codeborne.selenide.Selenide.$x;

public class PatchPage extends BasePage {
    SelenideElement selectConfigBtn = $x("//clv-select[contains(@ng-model, \"configuration\")]//button");
    @Getter
    SelenideElement confgListItem = $x("//*[contains(text(), \"AT_INSTALLATION\")]");
    SelenideElement createPatchBtn = $x("//*[contains(@ng-click, \"createNewPatch\")]");
    SelenideElement udfPatchOwnerBtn = $x("//*[contains(text(), \"Владелец патча\")]" +
            "/ancestor::div[contains(@class, \"form-group\")]" +
            "//button[not(contains(@class, \"clv-select-toggle\"))]");
    SelenideElement saveBtn = $x("//*[contains(@ng-click, \"createNewPatch\")]");
    SelenideElement taskNameField = $x("//input[@name='taskName']");


    public PatchPage setConfiguration() {
        elActions.click(selectConfigBtn);
        elActions.click(confgListItem);
        return this;
    }

    public PatchPage openPatchForm() {
        elActions.click(createPatchBtn);
        return this;
    }

    public String getAutoGeneratedName() {
        SelenideElement taskName = $x("//input[contains(@ng-model, 'task.name')]");
        return taskName.getDomProperty("value");
    }

    public String getAutoGeneratedShortName() {
        SelenideElement taskShortname = $x("//input[contains(@ng-model, 'task.shortname')]");
        return taskShortname.getDomProperty("value");
    }

    public String getAutoGeneratedBdkuCsclient() {
        SelenideElement bdkuCsclient = $x("//*[contains(text(), 'Код клиента CSC')]" +
                "/ancestor::*[contains(@class, 'form-group')]//input");
        return bdkuCsclient.getDomProperty("value");
    }

}
