package com.ts.common.ui.pages.portlets;

import com.codeborne.selenide.Condition;
import com.codeborne.selenide.ElementsCollection;
import com.codeborne.selenide.SelenideElement;
import com.ts.common.asserts.UiAsserts;
import com.ts.common.ui.pages.BasePage;
import lombok.Getter;

import static com.codeborne.selenide.Condition.visible;
import static com.codeborne.selenide.Selenide.$$x;
import static com.codeborne.selenide.Selenide.$x;

public class PatchPage extends BasePage {
    SelenideElement selectConfigBtn = $x("//clv-select[contains(@ng-model, \"configuration\")]//button");
    @Getter
    SelenideElement confgListItem = $x("//*[contains(text(), \"AT_INSTALLATION\")]");
    SelenideElement createPatchBtn = $x("//*[contains(@ng-click, \"createNewPatch\")]");
    SelenideElement udfPatchOwnerBtn = $x("//*[contains(text(), \"Владелец патча\")]" +
            "/ancestor::div[contains(@class, \"form-group\")]" +
            "//button[not(contains(@class, \"clv-select-toggle\"))]");
    SelenideElement saveBtn = $x("//*[contains(@ng-click, \"createNewPatch\")]");
    SelenideElement taskNameField = $x("//input[@name='taskName']");


    public PatchPage setConfiguration() {
        elActions.click(selectConfigBtn);
        elActions.click(confgListItem);
        return this;
    }

    public PatchPage openTaskForm() {
        elActions.click(createPatchBtn);
        return this;
    }

    public PatchPage saveTaskForm() {
        elActions.click(saveBtn);
        return this;
    }

    public PatchPage udfPatchOwnerIsPresent() {
        udfPatchOwnerBtn.shouldNot(Condition.exist);
        return this;
    }

    public void alertIsPresent(String fieldName, boolean present) {
        SelenideElement alert = $x("//*[contains(text(), \"" + fieldName + "\")]" +
                "/ancestor::*[contains(@class, \"form-group\")]//udf-edit-error/div[not(contains(@class, \"ng-hide\"))]");

        if (present) {
            UiAsserts.assertThat(alert).isElementAccordCondition(Condition.exist);
        } else {
            UiAsserts.assertThat(alert).isElementNotAccordCondition(Condition.exist);
        }
    }

    public int presentFieldsCount() {
        ElementsCollection fieldLabel = $$x("//label[contains(@class, 'control-label')]");
        return fieldLabel.size();
    }

    public String getAutoGeneratedName() {
        SelenideElement taskName = $x("//input[contains(@ng-model, 'task.name')]");
        return taskName.getDomProperty("value");
    }

    public String getAutoGeneratedShortName() {
        SelenideElement taskShortname = $x("//input[contains(@ng-model, 'task.shortname')]");
        return taskShortname.getDomProperty("value");
    }

    public String getAutoGeneratedBdkuCsclient() {
        SelenideElement bdkuCsclient = $x("//*[contains(text(), 'Код клиента CSC')]" +
                "/ancestor::*[contains(@class, 'form-group')]//input");
        return bdkuCsclient.getDomProperty("value");
    }

}
