package com.ts.common.entitites.commonEntities;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.ts.common.entitites.BaseEntity;
import com.ts.common.entitites.commonEntities.udf.*;
import com.ts.common.enums.Type;
import lombok.*;
import lombok.experimental.FieldDefaults;
import lombok.extern.jackson.Jacksonized;
import lombok.extern.slf4j.Slf4j;

import static com.ts.common.enums.Type.*;

@Slf4j
@Builder
@Getter
@Setter
@ToString
@NoArgsConstructor
@AllArgsConstructor
@Jacksonized
@JsonIgnoreProperties(ignoreUnknown = true)
@FieldDefaults(level = AccessLevel.PRIVATE)
public class Udfs extends BaseEntity {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfUser udfUser;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfUser secondUdfUser;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfUser thirdUdfUser;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfUser fourthUdfUser;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfMultiList udfMultiList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfMultiList secondUdfMultiList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfMultiList thirdUdfMultiList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfList udfList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfList secondUdfList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfList thirdUdfList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfList fourthUdfList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfList fifthUdfList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfList sixthUdfList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfList seventhUdfList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfList eighthUdfList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfList ninethUdfList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfList tenthUdfList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfList eleventhUdfList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfList twelfthUdfList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfList thirteenthUdfList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfList fourteenthUdfList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfList fifteenthUdfList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfString udfString;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfString secondUdfString;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfString thirdUdfString;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfString fourthUdfString;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfString fifthUdfString;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfString sixthUdfString;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfDouble udfDouble;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfDouble secondUdfDouble;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfDouble thirdUdfDouble;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfDouble fourthUdfDouble;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfDouble fifthUdfDouble;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfDouble sixthUdfDouble;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfDouble seventhUdfDouble;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfDouble eighthUdfDouble;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfDate udfDate;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfDate secondUdfDate;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfDate thirdUdfDate;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfTask udfTask;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfTask secondUdfTask;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfTask thirdUdfTask;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfLink udfLink;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfTask fourthUdfTask;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfTask sixthUdfTask;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfTask fifthUdfTask;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfTask seventhUdfTask;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfTask eighthUdfTask;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfTask ninethUdfTask;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfMemo udfMemo;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfMemo secondUdfMemo;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfMemo thirdUdfMemo;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfMemo fourthUdfMemo;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfMemo fifthUdfMemo;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfMemo sixthUdfMemo;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfMemo seventhUdfMemo;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfMemo eighthUdfMemo;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfMemo ninethUdfMemo;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfMemo tenthUdfMemo;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfMemo eleventhUdfMemo;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfMemo twelvethUdfMemo;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfInteger udfInteger;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfInteger secondUdfInteger;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfInteger thirdUdfInteger;

    public enum UdfSd {
        UDF_WORKTASK_CUSTOMTYPE("UDF_WORKTASK_CUSTOMTYPE", LIST),
        UDF_CDP_CUSTOMER("UDF_CDP_CUSTOMER", LIST),
        UDF_INSTALLATION_SDPROJECT("UDF_INSTALLATION_SDPROJECT", TASK),
        UDF_REGISTRY_FOLDER("UDF_REGISTRY_FOLDER", TASK),
        UDF_REGISTRY_SUPPORT("UDF_REGISTRY_SUPPORT", TASK),
        UDF_MIS_TPRJ("UDF_MIS_TPRJ", LIST),
        UDF_REGISTRY_LOB("UDF_REGISTRY_LOB", MULTILIST),
        UDF_SDPROJECT_SUPPORTTYPE("UDF_SDPROJECT_SUPPORTTYPE", LIST),
        UDF_SD_INTERNPROJECT("UDF_SD_INTERNPROJECT", TASK),
        UDF_SD_COST1CAT("UDF_SD_COST1CAT", INTEGER),
        UDF_SD_COST2CAT("UDF_SD_COST2CAT", INTEGER),
        UDF_SD_COST3CAT("UDF_SD_COST3CAT", INTEGER),
        UDF_PROJECT_MANAGING("UDF_PROJECT_MANAGING", LIST),
        UDF_PROJECT_MEMBERCODEREVIEW("UDF_PROJECT_MEMBERCODEREVIEW", LIST),
        UDF_SDFEATURE_STAGE("UDF_SDFEATURE_STAGE", LIST),
        UDF_MIS_SERVICE("UDF_MIS_SERVICE", LIST),
        UDF_SD_RESPONSIBLE_PARTY("UDF_SD_RESPONSIBLE_PARTY", LIST),
        UDF_SD_CLARIFYINGQUESTIONDATE("UDF_SD_CLARIFYINGQUESTIONDATE", DATE),
        UDF_SD_SLASTATUS("UDF_SD_SLASTATUS", STRING),
        UDF_SDDEV_CONDITIONSACCEPTED("UDF_SDDEV_CONDITIONSACCEPTED", LIST),
        UDF_WORKTASK_ADDTRSTWATCHINREQST("UDF_WORKTASK_ADDTRSTWATCHINREQST", LIST),
        UDF_WORKTASK_ADDWATCHERINREQST("UDF_WORKTASK_ADDWATCHERINREQST", LIST),
        UDF_WORKTASK_CHANGEWORKERINRQST("UDF_WORKTASK_CHANGEWORKERINRQST", LIST),
        UDF_WORKTASK_REASONERROR("UDF_WORKTASK_REASONERROR", LIST),
        UDF_WORKTASK_DEVREGVIOLATION("UDF_WORKTASK_DEVREGVIOLATION", LIST),
        UDF_WORKTASK_FROMSDREQUEST("UDF_WORKTASK_FROMSDREQUEST", LIST),
        UDF_WORKTASK_DEPENDBF("UDF_WORKTASK_DEPENDBF", TASK),
        UDF_WORKTASK_ANNOTATION("UDF_WORKTASK_ANNOTATION", MEMO),
        UDF_WORKTASK_WAYCODEREVIEW("UDF_WORKTASK_WAYCODEREVIEW", LIST),
        UDF_PROBLEMAREA("UDF_PROBLEMAREA", LIST),
        UDF_COREBUILDTYPE("UDF_COREBUILDTYPE", LIST),
        UDF_COMPONENTBUILDTYPE("UDF_COMPONENTBUILDTYPE", LIST),
        UDF_WORKTASK_BRANCH("UDF_WORKTASK_BRANCH", STRING),
        UDF_COREBUILD("UDF_COREBUILD", STRING),
        UDF_COMPONENTBUILD("UDF_COMPONENTBUILD", STRING),
        UDF_DATABASES("UDF_DATABASES", STRING),
        UDF_WORKTASK_ANALYSISFD("UDF_WORKTASK_ANALYSISFD", DATE),
        UDF_WORKTASK_ANALYSIS("UDF_WORKTASK_ANALYSIS", LIST),
        UDF_CDP_ACCEPTANCE("UDF_CDP_ACCEPTANCE", LIST),
        UDF_WORKTASK_COMPLEXITYLEVEL("UDF_WORKTASK_COMPLEXITYLEVEL", LIST),
        UDF_WORKTASK_QUALITY("UDF_WORKTASK_QUALITY", LIST),
        UDF_PRGAREA("UDF_PRGAREA", MULTILIST),
        UDF_L10N("UDF_L10N", MULTILIST),
        UDF_SD_TRUSTEDWATCHER("UDF_SD_TRUSTEDWATCHER", USER),
        UDF_WORKTASK_NEWAUTHOR_MSG("UDF_WORKTASK_NEWAUTHOR_MSG", USER),
        UDF_SLA_CONSULTPROVIDEDATE("UDF_SLA_CONSULTPROVIDEDATE", STRING),
        UDF_WATCHER("UDF_WATCHER", USER),
        UDF_SDQUESTION_NEWAUTHOR_MSG("UDF_SDQUESTION_NEWAUTHOR_MSG", USER),
        UDF_SDQUESTION_LINK("UDF_SDQUESTION_LINK", TASK),
        UDF_WORKTASK_ERRORTASK("UDF_WORKTASK_ERRORTASK", TASK),
        UDF_REALIZATION_DECISION("UDF_REALIZATION_DECISION", MEMO),
        UDF_REQ_LINKED("UDF_REQ_LINKED", TASK),
        UDF_SDFEATURE_IMPLSTATEMENT("UDF_SDFEATURE_IMPLSTATEMENT", MEMO),
        UDF_SDFEATURE_IMPLSTATEMENTFILE("UDF_SDFEATURE_IMPLSTATEMENTFILE", STRING),
        UDF_SOLUTION_PERIOD("UDF_SOLUTION_PERIOD", LIST),
        UDF_CUSTOMIZATION_FLAG("UDF_CUSTOMIZATION_FLAG", LIST),
        UDF_LOCALIZATION_FLAG("UDF_LOCALIZATION_FLAG", LIST),
        UDF_CDP_WT("UDF_CDP_WT", LIST),
        UDF_WORKTASK_GENUSEFUTAG("UDF_WORKTASK_GENUSEFUTAG", LIST),
        UDF_SOLUTION_IMPLTYPE("UDF_SOLUTION_IMPLTYPE", LIST),
        UDF_SOLUTION_CREATEGAPFEATURE("UDF_SOLUTION_CREATEGAPFEATURE", LIST),
        UDF_ROLE_CURRENT("UDF_ROLE_CURRENT", LIST),
        UDF_REQ_APRV_ANLYSMANAGER("UDF_REQ_APRV_ANLYSMANAGER", LIST),
        UDF_REQ_APRV_IMPLSMANAGER("UDF_REQ_APRV_IMPLSMANAGER", LIST),
        UDF_ROLE_FIRST_LINE("UDF_ROLE_FIRST_LINE", USER),
        UDF_SD_TASK_CODE("UDF_SD_TASK_CODE", LIST),
        UDF_WORKTASK_SEVERITY("UDF_WORKTASK_SEVERITY", LIST),
        UDF_WORKTASK_NEEDTECHTESTING("UDF_WORKTASK_NEEDTECHTESTING", LIST),
        UDF_WORKTASK_LANGUAGES("UDF_WORKTASK_LANGUAGES", LIST),
        UDF_WORKTASK_COMPLEXITY("UDF_WORKTASK_COMPLEXITY", LIST),
        UDF_WORKTASK_BUSINESSTRIP("UDF_WORKTASK_BUSINESSTRIP", LIST),
        UDF_WORKTASK_NEEDNEO("UDF_WORKTASK_NEEDNEO", LIST),
        UDF_WORKTASK_NEEDWORKSAMPLES("UDF_WORKTASK_NEEDWORKSAMPLES", LIST),
        UDF_WORKTASK_SANCTION("UDF_WORKTASK_SANCTION", LIST),
        UDF_WORKTASK_VACANCYPRIORITY("UDF_WORKTASK_VACANCYPRIORITY", LIST),
        UDF_SD_RELATED_TASK_CODES("UDF_SD_RELATED_TASK_CODES", MULTILIST),
        UDF_WORKTASK_QUALIFICATION("UDF_WORKTASK_QUALIFICATION", MULTILIST),
        UDF_WORKTASK_CITY("UDF_WORKTASK_CITY", MULTILIST),
        UDF_SD_MODULE("UDF_SD_MODULE", TASK),
        UDF_SD_HELPDEADLINE("UDF_SD_HELPDEADLINE", DATE),
        UDF_WORKTASK_DEPENDTASKFNC("UDF_WORKTASK_DEPENDTASKFNC", TASK),
        UDF_RELEASE_BRANCHES("UDF_RELEASE_BRANCHES", TASK),
        UDF_RELEASE_STANDS("UDF_RELEASE_STANDS", TASK),
        UDF_RELEASE_INSTALLATION("UDF_RELEASE_INSTALLATION", TASK),
        UDF_RELEASE_NUMBER("UDF_RELEASE_NUMBER", STRING),
        UDF_RELEASE_ACTUAL_USAGE("UDF_RELEASE_ACTUAL_USAGE", DATE),
        UDF_SD_NOMODULE_REASON("UDF_SD_NOMODULE_REASON", STRING),
        UDF_SDFEATURE_LEGALREQ_DOC("UDF_SDFEATURE_LEGALREQ_DOC", STRING),
        UDF_SDFEATURE_TYPEOTHER("UDF_SDFEATURE_TYPEOTHER", MEMO),
        UDF_SLAHELP_COST("UDF_SLAHELP_COST", STRING),
        UDF_ADVICE_PLANTD("UDF_ADVICE_PLANTD", DATE),
        UDF_BUDGET_FORMANAGE("UDF_BUDGET_FORMANAGE", DOUBLE),
        UDF_FINAL_ASSMT_DAY_STEPPLAN("UDF_FINAL_ASSMT_DAY_STEPPLAN", MEMO),
        UDF_IMPL_BUDGET("UDF_IMPL_BUDGET", MEMO),
        UDF_ACCEPT_BUDGET("UDF_ACCEPT_BUDGET", MEMO),
        UDF_SD_DEADLINETEMPFIX("UDF_SD_DEADLINETEMPFIX", DATE),
        UDF_SDDEV_LCOSTCHGDATE("UDF_SDDEV_LCOSTCHGDATE", DATE),
        UDF_TOTAL_PRELIM_OPTIMK_BUDGET("UDF_TOTAL_PRELIM_OPTIMK_BUDGET", DOUBLE),
        UDF_TOTAL_PRELIM_PESM_BUDGET("UDF_TOTAL_PRELIM_PESM_BUDGET", DOUBLE),
        UDF_TOTAL_PRELIM_AVG_BUDGET("UDF_TOTAL_PRELIM_AVG_BUDGET", DOUBLE),
        UDF_TOTAL_FINAL_OPT_BUDGET("UDF_TOTAL_FINAL_OPT_BUDGET", DOUBLE),
        UDF_TOTAL_FINAL_PESIM_BUDGET("UDF_TOTAL_FINAL_PESIM_BUDGET", DOUBLE),
        UDF_TOTAL_FINAL_AVG_BUDGET("UDF_TOTAL_FINAL_AVG_BUDGET", DOUBLE),
        UDF_LIST_AFFCTD_SYS("UDF_LIST_AFFCTD_SYS", MULTILIST),
        UDF_IMPL_SUCCESS_PLAN_LIMITATION("UDF_IMPL_SUCCESS_PLAN_LIMITATION", MEMO),
        UDF_POTENTIAL_FINAL_IMP_DATE("UDF_POTENTIAL_FINAL_IMP_DATE", DATE),
        UDF_POTENTIAL_DAY_FINALASSMT("UDF_POTENTIAL_DAY_FINALASSMT", DATE),
        UDF_POTENTIAL_PRELIM_IMPL_DATE("UDF_POTENTIAL_PRELIM_IMPL_DATE", DATE),
        UDF_DELIVERY_PATH_DATE("UDF_DELIVERY_PATH_DATE", DATE),
        UDF_WORK_PLAN("UDF_WORK_PLAN", MEMO),
        UDF_SD_DEADLINEFIX("UDF_SD_DEADLINEFIX", DATE),

        UDF_SDFEATURE_GENUSE("UDF_SDFEATURE_GENUSE", LIST),
        UDF_SDFEATURE_GENUSEOTHER("UDF_SDFEATURE_GENUSEOTHER", MEMO),

        UDF_SD_INLICENSE("UDF_SD_INLICENSE", LIST),

        UDF_CDP_BP("UDF_CDP_BP", LIST),

        UDF_WORKTASK_SDREQUEST("UDF_WORKTASK_SDREQUEST", TASK),

        UDF_WORKTASK_WORK("UDF_WORKTASK_WORK", TASK),

        UDF_RELEASE_COMPAT("UDF_RELEASE_COMPAT", TASK),

        UDF_SLA_URGANCYHELP("UDF_SLA_URGANCYHELP", LIST),

        UDF_SDDEV_CUSTOMTYPE("UDF_SDDEV_CUSTOMTYPE", LIST),

        UDF_SDDEV_DEVDECISION("UDF_SDDEV_DEVDECISION", LIST),

        UDF_SDDEV_GENUSE("UDF_SDDEV_GENUSE", LIST),

        UDF_SD_HELPKOEF("UDF_SD_HELPKOEF", DOUBLE),

        UDF_SDDEV_BUDGET1("UDF_SDDEV_BUDGET1", DOUBLE),

        UDF_SDDEV_BUDGET2("UDF_SDDEV_BUDGET2", DOUBLE),

        UDF_SD_LINKEDREQUEST("UDF_SD_LINKEDREQUEST", TASK),

        UDF_WORKTASK_TESTTASK("UDF_WORKTASK_TESTTASK", TASK),

        UDF_SD_REPEATREQUEST("UDF_SD_REPEATREQUEST", TASK),

        UDF_SD_CLIENTWATCHERS("UDF_SD_CLIENTWATCHERS", STRING),

        UDF_WORKTASK_VACANCYREASON("UDF_WORKTASK_VACANCYREASON", STRING),

        UDF_WORKTASK_TECHTESTING("UDF_WORKTASK_TECHTESTING", STRING),

        UDF_WORKTASK_JOBAPPLICANTCOMMENT("UDF_WORKTASK_JOBAPPLICANTCOMMENT", STRING),

        UDF_WORKTASK_LINE("UDF_WORKTASK_LINE", STRING),

        UDF_BDKU_CONFIGURATION("UDF_BDKU_CONFIGURATION", TASK),

        UDF_SD_REMOTEID("UDF_SD_REMOTEID", STRING),

        UDF_SD_INITPERSON("UDF_SD_INITPERSON", STRING),

        UDF_SLABUG_TEMPPROVIDEDATE("UDF_SLABUG_TEMPPROVIDEDATE", STRING),

        UDF_ACTUAL_PRELIM_BUDGET("UDF_ACTUAL_PRELIM_BUDGET", DOUBLE),

        UDF_SD_NOTLIMITEDWORK("UDF_SD_NOTLIMITEDWORK", LIST),

        UDF_WORKTASK_SOURCETYPE("UDF_WORKTASK_SOURCETYPE", LIST),

        UDF_SD_PROVIDEDHELPDEADLINE("UDF_SD_PROVIDEDHELPDEADLINE", DATE),

        UDF_SD_AUTHORCLIENT_MSG("UDF_SD_AUTHORCLIENT_MSG", USER),

        UDF_SDBUG_PRIORITYBUG("UDF_SDBUG_PRIORITYBUG", LIST),

        UDF_EVALUATING_REQUEST_EXECUTION("UDF_EVALUATING_REQUEST_EXECUTION", LIST),

        UDF_SD_CLOSEREASON("UDF_SD_CLOSEREASON", LIST),

        UDF_SD_REMOTEACCESS("UDF_SD_REMOTEACCESS", LIST),

        UDF_ROLE_DEVELOPER("UDF_ROLE_DEVELOPER", USER),

        UDF_ROLE_TESTER("UDF_ROLE_TESTER", USER),

        UDF_SD_REMOTEACCESSINFO("UDF_SD_REMOTEACCESSINFO", MEMO),

        UDF_SDFEATURE_TYPE("UDF_SDFEATURE_TYPE", LIST),

        UDF_WORKTASK_AWAITTD("UDF_WORKTASK_AWAITTD", DATE),

        UDF_WORKTASK_AWAITBUDGET("UDF_WORKTASK_AWAITBUDGET", DOUBLE),

        UDF_CDP_NORMBUDGET("UDF_CDP_NORMBUDGET", DOUBLE),

        UDF_WORKTASK_PLANBUDGET("UDF_WORKTASK_PLANBUDGET", DOUBLE),

        UDF_WORKTASK_FIRSTPLANBUDGET("UDF_WORKTASK_FIRSTPLANBUDGET", DOUBLE),

        UDF_CDP_STEPPLAN("UDF_CDP_STEPPLAN", MEMO),

        UDF_EVALUATING_REQUEST_COMMENT("UDF_EVALUATING_REQUEST_COMMENT", MEMO),

        UDF_WORKTASK_TESTPLAN("UDF_WORKTASK_TESTPLAN", MEMO),

        UDF_WORKTASK_FILES("UDF_WORKTASK_FILES", MEMO),

        UDF_CDP_STEPPROGRESS("UDF_CDP_STEPPROGRESS", MEMO),

        UDF_WORKTASK_ERRORDESCRIPTION("UDF_WORKTASK_ERRORDESCRIPTION", MEMO),

        UDF_WORKTASK_MAINDUTIES("UDF_WORKTASK_MAINDUTIES", MEMO),

        UDF_WORKTASK_RATIONALEVACANCY("UDF_WORKTASK_RATIONALEVACANCY", MEMO),

        UDF_WORKTASK_MAINREQUIREMENTS("UDF_WORKTASK_MAINREQUIREMENTS", MEMO),

        UDF_WORKTASK_PROJECTDESCRIPTION("UDF_WORKTASK_PROJECTDESCRIPTION", MEMO),

        UDF_WORKTASK_RESPFOREPLAN("UDF_WORKTASK_RESPFOREPLAN", USER),

        UDF_WORKTASK_TASKALLOCATION("UDF_WORKTASK_TASKALLOCATION", MEMO),

        UDF_SDBUG_CONSEQ("UDF_SDBUG_CONSEQ", MEMO),

        UDF_WORKTASK_SUPERVISER("UDF_WORKTASK_SUPERVISER", USER),

        UDF_WORKTASK_SANCTIONER("UDF_WORKTASK_SANCTIONER", USER),

        UDF_WORKTASK_DEP("UDF_WORKTASK_DEP", USER),

        UDF_WORKTASK_JOBAPPLICANT("UDF_WORKTASK_JOBAPPLICANT", USER),

        UDF_WORKTASK_LINEMANAGER("UDF_WORKTASK_LINEMANAGER", USER),

        UDF_CDP_BL("UDF_CDP_BL", LIST),

        UDF_WORKTASK_REASONFOREPLAN("UDF_WORKTASK_REASONFOREPLAN", LIST),

        UDF_WORKTASK_DISTTOALL("UDF_WORKTASK_DISTTOALL", LIST),

        UDF_SDFEATURE_PAYDCS("UDF_SDFEATURE_PAYDCS", LIST),
        UDF_SDFEATURE_PAYLPR("UDF_SDFEATURE_PAYLPR", LIST),
        UDF_SDFEATURE_PAYDCSREASON("UDF_SDFEATURE_PAYDCSREASON", MEMO),
        UDF_SLA_ENDCOSTBUDGET("UDF_SLA_ENDCOSTBUDGET", STRING),

        UDF_WORKTASK_REASSIGNCONTROL_MSG("UDF_WORKTASK_REASSIGNCONTROL_MSG", LIST),

        UDF_SLA_CLIENTGENUSE("UDF_SLA_CLIENTGENUSE", LIST),

        UDF_CDP_ACCEPTANCE_STATUS("UDF_CDP_ACCEPTANCE_STATUS", LIST),

        STDT_HANDLER("STDT_HANDLER", USER),

        UDF_CLIENT_HANDLER("UDF_CLIENT_HANDLER", USER),

        UDF_SDFEATURE_CANCELREASON("UDF_SDFEATURE_CANCELREASON", LIST),

        UDF_SDFEATURE_AGREEDDECISION("UDF_SDFEATURE_AGREEDDECISION", MEMO),
        UDF_SDFEATURE_NOTE("UDF_SDFEATURE_NOTE", MEMO),
        UDF_SDFEATURE_TESTCASE("UDF_SDFEATURE_TESTCASE", MEMO),

        UDF_SLA_AWAITCOST("UDF_SLA_AWAITCOST", STRING),
        UDF_SLA_PRECOSTBUDGET("UDF_SLA_PRECOSTBUDGET", STRING),
        UDF_SLA_AWAITENDCOSTBUDGET("UDF_SLA_AWAITENDCOSTBUDGET", STRING),

        UDF_SLA_IMPLPLANTD_PRE("UDF_SLA_IMPLPLANTD_PRE", STRING),

        UDF_SLA_FINALESTIMATIONDATE("UDF_SLA_FINALESTIMATIONDATE", DATE),

        UDF_SDFEATURE_IMPLBUDGET("UDF_SDFEATURE_IMPLBUDGET", DOUBLE),

        UDF_PRODUCT("UDF_PRODUCT", TASK),

        UDF_COMPONENT("UDF_COMPONENT", TASK),

        UDF_RELEASE_PREFIX("UDF_RELEASE_PREFIX", STRING),

        UDF_RELEASE_REPOURL("UDF_RELEASE_REPOURL", LINK),

        UDF_RELEASE_MODULE_DEPENDENCIES("UDF_RELEASE_MODULE_DEPENDENCIES", TASK),

        UDF_RELEASE_INITREV("UDF_RELEASE_INITREV", STRING),

        UDF_RELEASE_FUNCT("UDF_RELEASE_FUNCT", STRING),

        UDF_SDFEATURE_DETAILBUDGET("UDF_SDFEATURE_DETAILBUDGET", DOUBLE),

        UDF_SDFEATURE_DOCREVISION("UDF_SDFEATURE_DOCREVISION", LIST),
        UDF_SDFEATURE_ANALYSISSPEED("UDF_SDFEATURE_ANALYSISSPEED", LIST),
        UDF_SDFEATURE_WORKQUALITY("UDF_SDFEATURE_WORKQUALITY", LIST),
        UDF_SDFEATURE_WORKSPEED("UDF_SDFEATURE_WORKSPEED", LIST),

        UDF_SD_MUSTSETTINGINSTAL("UDF_SD_MUSTSETTINGINSTAL", LIST),

        UDF_WORKTASK_CREATETESTTASK("UDF_WORKTASK_CREATETESTTASK", LIST),

        UDF_WORKTASK_ACCEPTOR("UDF_WORKTASK_ACCEPTOR", USER),

        UDF_SLABUG_PERMPROVIDEDATE("UDF_SLABUG_PERMPROVIDEDATE", STRING),

        UDF_SD_PATCHNUMBER("UDF_SD_PATCHNUMBER", STRING),

        UDF_SDFEATUREPLANTD("UDF_SDFEATUREPLANTD", DATE),
        UDF_SDFEATURE_LEGALREQ("UDF_SDFEATURE_LEGALREQ", DATE),
        UDF_SDFEATURE_CUSTOMDEV("UDF_SDFEATURE_CUSTOMDEV", LIST),

        UDF_SLA_IMPLDEADLINE("UDF_SLA_IMPLDEADLINE", STRING),

        UDF_SDFEATURE_OVERLIMITREASON("UDF_SDFEATURE_OVERLIMITREASON", STRING),

        UDF_WORKTASK_POSITION("UDF_WORKTASK_POSITION", STRING),

        UDF_SLA_RESULTCOST("UDF_SLA_RESULTCOST", STRING),

        UDF_ROLE_WORKER("UDF_ROLE_WORKER", USER),

        UDF_ROLE_RESET("UDF_ROLE_RESET", LIST),

        UDF_WORKTASK_INREPLAN("UDF_WORKTASK_INREPLAN", LIST),

        UDF_REGPROJECT("UDF_REGPROJECT", TASK),
        UDF_BDKU_CSCCLIENT("UDF_BDKU_CSCCLIENT", STRING),

        UDF_WORKTASK_PLANTD("UDF_WORKTASK_PLANTD", DATE),

        UDF_WORKTASK_VACANCYPLANFD("UDF_WORKTASK_VACANCYPLANFD", DATE),

        UDF_WORKTASK_VACANCYSTARTD("UDF_WORKTASK_VACANCYSTARTD", DATE),

        STDT_SUBMITTER("STDT_SUBMITTER", USER),

        UDF_PARTICIPANTS("UDF_PARTICIPANTS", USER),

        UDF_WORKTASK_REPLAN_N("UDF_WORKTASK_REPLAN_N", INTEGER),

        UDF_WORKTASK_NUMBERAPPLICANTS("UDF_WORKTASK_NUMBERAPPLICANTS", INTEGER),

        UDF_TASK_SECONDWARNINGDAYS("UDF_TASK_SECONDWARNINGDAYS", INTEGER),

        UDF_TASK_ACTUAL_MONTHS("UDF_TASK_ACTUAL_MONTHS", INTEGER),

        UDF_WORKTASK_PLANFD("UDF_WORKTASK_PLANFD", DATE);

        public final String udfId;
        public final Type type;

        UdfSd(String udfId, Type type) {
            this.udfId = udfId;
            this.type = type;
        }
    }
}
