package com.ts.common.entitites.commonEntities;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.ts.common.entitites.BaseEntity;
import com.ts.common.entitites.commonEntities.udf.*;
import com.ts.common.enums.Type;
import lombok.*;
import lombok.experimental.FieldDefaults;
import lombok.extern.jackson.Jacksonized;
import lombok.extern.slf4j.Slf4j;

import static com.ts.common.enums.Type.*;

@Slf4j
@Builder
@Getter
@Setter
@ToString
@NoArgsConstructor
@AllArgsConstructor
@Jacksonized
@JsonIgnoreProperties(ignoreUnknown = true)
@FieldDefaults(level = AccessLevel.PRIVATE)
public class Udfs extends BaseEntity {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfUser udfUser;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfUser secondUdfUser;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfUser thirdUdfUser;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfList udfList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfList secondUdfList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfList thirdUdfList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfList fourthUdfList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfList fifthUdfList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfString udfString;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfString secondUdfString;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfString thirdUdfString;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfDouble udfDouble;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfDouble secondUdfDouble;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfDate udfDate;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfTask udfTask;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfTask secondUdfTask;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfTask thirdUdfTask;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UdfLink udfLink;

//    public BaseEntity getUdfByUdfId(String udfId, String) {
//        this.getClass().getField()
//    }

    public enum UdfSd {
        UDF_WORKTASK_ADDTRSTWATCHINREQST("UDF_WORKTASK_ADDTRSTWATCHINREQST", LIST),
        UDF_WORKTASK_ADDWATCHERINREQST("UDF_WORKTASK_ADDWATCHERINREQST", LIST),
        UDF_WORKTASK_CHANGEWORKERINRQST("UDF_WORKTASK_CHANGEWORKERINRQST", LIST),
        UDF_WORKTASK_DEPENDBF("UDF_WORKTASK_DEPENDBF", TASK),
        UDF_WORKTASK_ANNOTATION("UDF_WORKTASK_ANNOTATION", MEMO),
        UDF_WORKTASK_WAYCODEREVIEW("UDF_WORKTASK_WAYCODEREVIEW", LIST),
        UDF_WORKTASK_BRANCH("UDF_WORKTASK_BRANCH", STRING),
        UDF_WORKTASK_ANALYSISFD("UDF_WORKTASK_ANALYSISFD", DATE),
        UDF_CDP_ACCEPTANCE("UDF_CDP_ACCEPTANCE", LIST),
        UDF_WORKTASK_COMPLEXITYLEVEL("UDF_WORKTASK_COMPLEXITYLEVEL", LIST),
        UDF_PRGAREA("UDF_PRGAREA", MULTILIST),
        UDF_SD_TRUSTEDWATCHER("UDF_SD_TRUSTEDWATCHER", USER),
        UDF_SLA_CONSULTPROVIDEDATE("UDF_SLA_CONSULTPROVIDEDATE", STRING),
        UDF_WATCHER("UDF_WATCHER", USER),
        UDF_SDQUESTION_LINK("UDF_SDQUESTION_LINK", TASK),
        UDF_REALIZATION_DECISION("UDF_REALIZATION_DECISION", MEMO),
        UDF_REQ_LINKED("UDF_REQ_LINKED", TASK),
        UDF_SDFEATURE_IMPLSTATEMENT("UDF_SDFEATURE_IMPLSTATEMENT", MEMO),
        UDF_SDFEATURE_IMPLSTATEMENTFILE("UDF_SDFEATURE_IMPLSTATEMENTFILE", STRING),
        UDF_SOLUTION_PERIOD("UDF_SOLUTION_PERIOD", LIST),
        UDF_CUSTOMIZATION_FLAG("UDF_CUSTOMIZATION_FLAG", LIST),
        UDF_LOCALIZATION_FLAG("UDF_LOCALIZATION_FLAG", LIST),
        UDF_CDP_WT("UDF_CDP_WT", LIST),
        UDF_WORKTASK_GENUSEFUTAG("UDF_WORKTASK_GENUSEFUTAG", LIST),
        UDF_SOLUTION_IMPLTYPE("UDF_SOLUTION_IMPLTYPE", LIST),
        UDF_SOLUTION_CREATEGAPFEATURE("UDF_SOLUTION_CREATEGAPFEATURE", LIST),
        UDF_ROLE_CURRENT("UDF_ROLE_CURRENT", LIST),
        UDF_SD_TASK_CODE("UDF_SD_TASK_CODE", LIST),
        UDF_SD_RELATED_TASK_CODES("UDF_SD_RELATED_TASK_CODES", MULTILIST),
        UDF_SD_MODULE("UDF_SD_MODULE", TASK),
        UDF_SD_NOMODULE_REASON("UDF_SD_NOMODULE_REASON", STRING),
        UDF_SLAHELP_COST("UDF_SLAHELP_COST", STRING),
        UDF_ADVICE_PLANTD("UDF_ADVICE_PLANTD", DATE),
        UDF_SDFEATURE_GENUSE("UDF_SDFEATURE_GENUSE", LIST),
        UDF_WORKTASK_SDREQUEST("UDF_WORKTASK_SDREQUEST", TASK),
        UDF_WORKTASK_WORK("UDF_WORKTASK_WORK", TASK),
        UDF_SLA_URGANCYHELP("UDF_SLA_URGANCYHELP", LIST),
        UDF_SD_HELPKOEF("UDF_SD_HELPKOEF", DOUBLE),
        UDF_SD_LINKEDREQUEST("UDF_SD_LINKEDREQUEST", TASK),
        UDF_SD_REPEATREQUEST("UDF_SD_REPEATREQUEST", TASK),
        UDF_SD_CLIENTWATCHERS("UDF_SD_CLIENTWATCHERS", STRING),
        UDF_BDKU_CONFIGURATION("UDF_BDKU_CONFIGURATION", TASK),
        UDF_SD_REMOTEID("UDF_SD_REMOTEID", STRING),
        UDF_SD_INITPERSON("UDF_SD_INITPERSON", STRING),
        UDF_SLABUG_TEMPPROVIDEDATE("UDF_SLABUG_TEMPPROVIDEDATE", STRING),
        UDF_SD_NOTLIMITEDWORK("UDF_SD_NOTLIMITEDWORK", LIST),
        UDF_WORKTASK_SOURCETYPE("UDF_WORKTASK_SOURCETYPE", LIST),
        UDF_SD_PROVIDEDHELPDEADLINE("UDF_SD_PROVIDEDHELPDEADLINE", DATE),
        UDF_SD_AUTHORCLIENT_MSG("UDF_SD_AUTHORCLIENT_MSG", USER),
        UDF_SDBUG_PRIORITYBUG("UDF_SDBUG_PRIORITYBUG", LIST),
        UDF_EVALUATING_REQUEST_EXECUTION("UDF_EVALUATING_REQUEST_EXECUTION", LIST),
        UDF_SD_CLOSEREASON("UDF_SD_CLOSEREASON", LIST),
        UDF_SD_REMOTEACCESS("UDF_SD_REMOTEACCESS", LIST),
        UDF_SDFEATURE_TYPE("UDF_SDFEATURE_TYPE", LIST),
        UDF_WORKTASK_SUPERVISER("UDF_WORKTASK_SUPERVISER", USER),
        UDF_CDP_BL("UDF_CDP_BL", LIST),

        UDF_SDFEATURE_PAYDCS("UDF_SDFEATURE_PAYDCS", LIST),

        UDF_SLA_CLIENTGENUSE("UDF_SLA_CLIENTGENUSE", LIST),

        STDT_HANDLER("STDT_HANDLER", USER),

        UDF_CLIENT_HANDLER("UDF_CLIENT_HANDLER", USER),

        UDF_SDFEATURE_CANCELREASON("UDF_SDFEATURE_CANCELREASON", LIST),

        UDF_SDFEATURE_AGREEDDECISION("UDF_SDFEATURE_AGREEDDECISION", MEMO),

        UDF_SLA_AWAITCOST("UDF_SLA_AWAITCOST", STRING),

        UDF_SLA_IMPLPLANTD_PRE("UDF_SLA_IMPLPLANTD_PRE", STRING),

        UDF_SLA_FINALESTIMATIONDATE("UDF_SLA_FINALESTIMATIONDATE", DATE),

        UDF_SDFEATURE_IMPLBUDGET("UDF_SDFEATURE_IMPLBUDGET", DOUBLE),

        UDF_PRODUCT("UDF_PRODUCT", TASK),

        UDF_RELEASE_PREFIX("UDF_RELEASE_PREFIX", STRING),

        UDF_RELEASE_REPOURL("UDF_RELEASE_REPOURL", LINK),

        UDF_RELEASE_MODULE_DEPENDENCIES("UDF_RELEASE_MODULE_DEPENDENCIES", TASK),

        UDF_RELEASE_INITREV("UDF_RELEASE_INITREV", STRING),

        UDF_RELEASE_FUNCT("UDF_RELEASE_FUNCT", STRING),

        UDF_SDFEATURE_DETAILBUDGET("UDF_SDFEATURE_DETAILBUDGET", DOUBLE),

        UDF_SDFEATURE_DOCREVISION("UDF_SDFEATURE_DOCREVISION", LIST),

        UDF_SLABUG_PERMPROVIDEDATE("UDF_SLABUG_PERMPROVIDEDATE", STRING),

        UDF_SDFEATUREPLANTD("UDF_SDFEATUREPLANTD", DATE),

        UDF_SLA_IMPLDEADLINE("UDF_SLA_IMPLDEADLINE", STRING),

        UDF_SLA_RESULTCOST("UDF_SLA_RESULTCOST", STRING),

        UDF_ROLE_WORKER("UDF_ROLE_WORKER", USER),

        UDF_ROLE_RESET("UDF_ROLE_RESET", LIST),

        UDF_REGPROJECT("UDF_REGPROJECT", TASK);

        public final String udfId;
        public final Type type;

        UdfSd(String udfId, Type type) {
            this.udfId = udfId;
            this.type = type;
        }
    }
}
