image: maven:3-jdk-11

stages:
  - test

test:
  stage: test

  script:
    - mvn compile test
    - allure generate target/allure-results

  artifacts:
    when: always
    name: "Allure Report"
    paths:
      - allure-report/*
    expire_in: 30 days
