package com.ts.common.enums;

import lombok.Getter;

public enum Tables {
    SLA_BUG("<table border=\"1px\" cellpadding=\"0\" cellspacing=\"0\" class=\"general\">\n\t<tbody>\n\t\t<tr>\n\t\t\t<th style=\"background-color: #EBF1F5; border: 1px solid #AAAAAA; color: #808080; font-size: 11px; font-weight: normal; text-align: right;\">Дата возникновения ошибки *</th>\n\t\t\t<td data-required=\"true\" width=\"50%\">&nbsp; &nbsp; &nbsp;test</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<th style=\"background-color: #EBF1F5; border: 1px solid #AAAAAA; color: #808080; font-size: 11px; font-weight: normal; text-align: right;\">Пользователь *</th>\n\t\t\t<td data-required=\"true\" width=\"50%\">test</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<th style=\"background-color: #EBF1F5; border: 1px solid #AAAAAA; color: #808080; font-size: 11px; font-weight: normal; text-align: right;\">Логин *</th>\n\t\t\t<td data-required=\"true\" width=\"50%\">test</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<th style=\"background-color: #EBF1F5; border: 1px solid #AAAAAA; color: #808080; font-size: 11px; font-weight: normal; text-align: right;\">Пароль *</th>\n\t\t\t<td data-nolink-after-hash=\"true\" data-required=\"true\" width=\"50%\">test</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<th style=\"background-color: #EBF1F5; border: 1px solid #AAAAAA; color: #808080; font-size: 11px; font-weight: normal; text-align: right;\">Тестовая инстанция *</th>\n\t\t\t<td data-required=\"true\" width=\"50%\">test</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<th style=\"background-color: #EBF1F5; border: 1px solid #AAAAAA; color: #808080; font-size: 11px; font-weight: normal; text-align: right;\">Дата операционного дня *</th>\n\t\t\t<td data-required=\"true\" width=\"50%\">test</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<th style=\"background-color: #EBF1F5; border: 1px solid #AAAAAA; color: #808080; font-size: 11px; font-weight: normal; text-align: right;\">Признак \"Ошибка\" при выполнении операции *</th>\n\t\t\t<td data-required=\"true\" width=\"50%\">test</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<th style=\"background-color: #EBF1F5; border: 1px solid #AAAAAA; color: #808080; font-size: 11px; font-weight: normal; text-align: right;\">АРМ пользователя</th>\n\t\t\t<td width=\"50%\">&nbsp; &nbsp; &nbsp;test</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<th style=\"background-color: #EBF1F5; border: 1px solid #AAAAAA; color: #808080; font-size: 11px; font-weight: normal; text-align: right;\">Код продукта</th>\n\t\t\t<td width=\"50%\">&nbsp; &nbsp; &nbsp;test</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<th style=\"background-color: #EBF1F5; border: 1px solid #AAAAAA; color: #808080; font-size: 11px; font-weight: normal; text-align: right;\">Дополнительно (любая информация, не попадающая под формат)</th>\n\t\t\t<td width=\"50%\">&nbsp; &nbsp; &nbsp;test</td>\n\t\t</tr>\n\t</tbody>\n</table>\n");
    @Getter
    private final String table;

    Tables(String table) {
        this.table = table;
    }
}
