package com.ts.common.enums;

public enum TaskStatuses {
    STATUS_WORKTASK_ONANALYSIS,
    STATUS_PROJECT_PLANNED,
    STATUS_SLAHELP_ANALIZING,
    STATUS_SLAHELP_WAITANALIZING,
    STATUS_SLAHELP_CONSULTED,
    STATUS_WORKTASK_INWORK,
    STATUS_WORKTASK_POSTPONED,
    STATUS_WORKTASK_DECLINED,
    STATUS_WORKTASK_ANALYSISFINISHED,
    STATUS_ADVICE_ANSWERED,
    STATUS_ADVICE_CLOSED,
    STATUS_ADVICE_AWAIT,
    STATUS_ADVICE_DECLINED,
    STATUS_WORKTASK_ASSIGNED,
    STATUS_ADVICE_CHANGED,
    STATUS_ADVICE_CONFIRM,
    STATUS_SLAHELP_CLOSED;
}
