package com.ts.common.enums;

public enum TaskType {

    SLA_HElP("SLAHELP"),
    CAT_CFGTASK("CFGTASK"),
    CAT_CFG_FOLDER("CAT_CFGFOLDER"),

    SLA_BUG("SLABUG"),

    SLA_FEATURE("SLAFEATURE"),
    POTENTIAL_GAP("POTENTIALGAP"),
    SOL_SELECTED("SOLSELECTED"),
    GAP_SOLUTION("GAPSOLUTION"),
    SD_HELP("SDHELP"),
    SD_QUESTION("SDQUESTION"),
    GAP("GAP"),
    ADVICE("ADVICE"),
    CODEREVIEW("CODEREVIEW"),
    SANCTION("SANCTION"),
    CONFIRMATION("CONFIRMATION"),
    RELEASE_MODULE("RELEASEMODULE"),
    DEV_TASK("DEVTASK"),
    CAT_TECHTASK("TECHTASK"),
    CAT_ACCEPTTASK("ACCEPTTASK"),
    CAT_DISTASK("DISTASK"),
    WORK_TASK("WORKTASK"),
    BUG_TASK("BUGTASK"),
    SD_BUG("SDBUG"),
    SD_DEV("SDDEV"),
    SD_IMPROVE("SDIMPROVE"),
    SD_DOC_IMPROVE("SDDOCIMPROVE"),
    SD_DOC_BUG("SDDOCBUG"),
    SD_OPTIMIZATION("SDOPTIMIZATION"),
    CONTINGENT("CONTINGENT"),
    ADMINJOB("ADMINJOB"),

    RELEASE("RELEASE");

    public final String type;

    TaskType(String type) {
        this.type = type;
    }

    public enum WorkTask {
        ADMIN_JOB("ADMINJOB"),
        OUT_COMMUNICATION("OUTCOMMUNICATION"),
        IN_COMMUNICATION("INCOMMUNICATION"),
        HELP_DESK_TASK("HELPDESKTASK"),
        LOCALIZATION("LOCALIZATION"),
        MIGRATION("MIGRATION"),
        AUTOTEST("AUTOTEST"),
        ANAL_TASK("ANALTASK"),
        CONSTR_ANAL_TASK("CONSTRANALTASK"),
        ACCEPT_TASK("ACCEPTTASK"),
        DEV_AUTOTEST("DEVAUTOTEST"),
        REG_TEST_TASK("REGTESTTASK"),
        TEST_TASK("TESTTASK"),
        QA_JOB("QAJOB"),
        MAINTENANCE("MAINTENANCE"),
        INFRASTRUCTURE("INFRASTRUCTURE"),
        CONSTRUCTOR("CONSTRUCTOR"),
        TEACH_CLIENT("TEACHCLIENT"),
        TEACH_ROLE("TEACHROLE"),
        FIRST_ANAL("FIRSTANAL"),
        BUSINESS_PROC("BUSINESPROC"),
        SUPPORT("SUPPORT"),
        PO_PROJECT("POPROJECT"),
        PERSONAL_JOB("PERSONALJOB"),
        BUSINESS_ANAL("BUSINESSANAL"),
        MANAGERS("MANAGERS"),
        DOC_TASK("DOCTASK");
        public final String type;

        WorkTask(String type) {
            this.type = type;
        }
    }


}
