username=ametaxa
second_username=nsolovey
clientUsername=apenkov@mtb.minsk.by
password=password
passwordProd=PilVinooniVliP
#???????????
role.organization=ROLE_ORGANIZATION
#===========??????
role.client=ROLE_CLIENT
#===========???????????
role.dep=ROLE_DEP
#===========?????????
role.worker=ROLE_WORKER
#===========???????? ???????
at.task.manager=AT_TASK_MANAGER
#===========???????? ???????
at.task.participant=AT_TASK_PARTICIPANT
#===========???????? ???????
at.support.manager=AT_SUPPORT_MANAGER
#===========???????? ?? ?????????????? ? ???????????
at.suppliermanager=AT_SUPPLIERMANAGER
#===========????????
at.task.analitic=AT_TASK_ANALITIC
#===========Account-????????
at.support.costmanager=AT_SUPPORT_COSTMANAGER
#===========???????? ?? ??????? ?????????
at.sdfeature.analysis.manager=AT_SDFEATURE_ANALYSIS_MANAGER
#===========???????? ???????
at.sdfeature.impl.manager=AT_SDFEATURE_IMPL_MANAGER
#===========??????? ??????????
at_contract_emp=AT_CONTRACT_EMP