username=ametaxa
second_username=nsolovey
clientUsername=apenkov@mtb.minsk.by
password=password
passwordProd=PilVinooniVliP
#???????????
role.organization=ROLE_ORGANIZATION
#===========??????
role.client=ROLE_CLIENT
#===========???????????
role.dep=ROLE_DEP
#===========?????????
role.worker=ROLE_WORKER
#===========???????? ???????
project.manager=AT_TASK_MANAGER
#===========???????? ???????
project.participant=AT_TASK_PARTICIPANT
#===========???????? ???????
manager.client=AT_SUPPORT_MANAGER
#===========???????? ?? ?????????????? ? ???????????
manager.supplier=AT_SUPPLIERMANAGER
#===========????????
analytic=AT_TASK_ANALITIC
#===========Account-????????
manager.account=AT_SUPPORT_COSTMANAGER
#===========???????? ?? ??????? ?????????
manager.feature=AT_SDFEATURE_ANALYSIS_MANAGER
#===========???????? ???????
manager.request=AT_SDFEATURE_IMPL_MANAGER
#===========??????? ??????????
manager.emp=AT_CONTRACT_EMP