package com.ts.integration.tests.ui.tc1563098;

import com.codeborne.selenide.Selenide;
import com.ts.common.application.database.dbEntities.GrTaskDbEntity;
import com.ts.common.application.database.dbTables.GrTaskTable;
import com.ts.common.controllers.folder.SdPatchFolderController;
import com.ts.common.controllers.installation.InstallationController;
import com.ts.common.entitites.commonEntities.Parent;
import com.ts.common.entitites.commonEntities.Udfs;
import com.ts.common.entitites.tasks.GeneralTask;
import com.ts.common.enums.Operations;
import com.ts.common.ui.pages.LoginPage;
import com.ts.common.ui.pages.portlets.PatchPage;
import com.ts.common.utils.DateUtils;
import com.ts.common.utils.InitEntities;
import com.ts.common.utils.WaitManager;
import com.ts.integration.tests.BaseUiTest;
import org.testng.Assert;
import org.testng.annotations.*;

import static com.codeborne.selenide.Selenide.open;
import static com.ts.common.entitites.commonEntities.Udfs.UdfSd.UDF_BDKU_CSCCLIENT;
import static com.ts.common.enums.TaskType.BDKU_INSTALLATION;
import static com.ts.common.enums.TaskType.SDPATCHFOLDER;
import static com.ts.common.utils.InitEntities.generateUdfString;


public class CheckPatchFormTest extends BaseUiTest {
    LoginPage loginPage;
    PatchPage patchPage;
    InstallationController installationController;
    SdPatchFolderController sdPatchFolderController;
    GeneralTask generalTask;
    Udfs udf;
    GrTaskTable grTaskTable;
    Parent parent;

    String url = "http://tsdev7.dev.colvir.ru/TrackStudio/app/portlet/patch?branch=AZPST";

    @BeforeClass(alwaysRun = true)
    public void beforeClass() {
        loginPage = trackStudioPages.getLoginPage();
        patchPage = trackStudioPages.getPatchPage();

        grTaskTable = dbHelper.getGrTaskTable();
        GrTaskDbEntity grTaskDbEntity = (GrTaskDbEntity) grTaskTable.receiveByTaskName("AT_INSTALLATION");

//        //генерация структуры данных для тестов
//        installationController = apiController.getInstallationController();
//        sdPatchFolderController = apiController.getSdPatchfolderController();
//        //grTaskTable = dbHelper.getGrTaskTable();
//        //GrTaskDbEntity grTaskDbEntity = (GrTaskDbEntity) grTaskTable.receiveByTaskNumber("462311");
//
//        parent = InitEntities.generateParent("818180a050c582480150c947cb252eb5", "462311");
//        generalTask = InitEntities.getGeneralTask(BDKU_INSTALLATION, Operations.CAT);
//        udf = InitEntities.refreshUdf();
//        generalTask.setName("AT_INSTALLATION");
//        generalTask.setParent(parent);
//        udf.setUdfString(generateUdfString(UDF_BDKU_CSCCLIENT, "AT_INSTALLATION"));
//        generalTask.refreshUdf(udf);
//        installationController.createInstallation(generalTask);
//
//        parent = InitEntities.generateParent(generalTask.getId(), generalTask.getNumber());
//        generalTask = InitEntities.getGeneralTask(SDPATCHFOLDER, Operations.CAT);
//        udf = InitEntities.refreshUdf();
//        generalTask.setName("AT_SDPATCHFOLDER");
//        generalTask.setParent(parent);
//        //udf.setUdfString(generateUdfString(UDF_BDKU_CSCCLIENT, "AT_INSTALLATION"));
//        generalTask.refreshUdf(udf);
//        sdPatchFolderController.createSdPatchFolder(generalTask);
    }

    @AfterMethod
    public void afterTest() {
        Selenide.clearBrowserCookies();
    }

    @Test(enabled = true)
    public void formByAdmin() {
        String user = "root";

        auth(url, user);
        patchPage.setConfiguration()
                .openTaskForm();

        //ждем прорисовки варнингов
        WaitManager.pause(2);

        //проверяем автогенерацию имени и кода задачи
        Assert.assertEquals(patchPage.getAutoGeneratedName(), "null-001");
        Assert.assertEquals(patchPage.getAutoGeneratedShortName(), "null-001");
        Assert.assertEquals(patchPage.getAutoGeneratedBdkuCsclient(), "AT_INSTALLATION");

        //проверяем количество отображаемых полей
        Assert.assertEquals(patchPage.presentFieldsCount(), 9);

        //проверяем наличие валидации полей
        patchPage.alertIsPresent("Ответственный", false);
        patchPage.alertIsPresent("Наблюдатели", false);
        patchPage.alertIsPresent("Владелец патча", true);
        patchPage.alertIsPresent("Плановая дата вывода из эксплуатации", false);
        patchPage.alertIsPresent("Код клиента CSC", false);
        patchPage.alertIsPresent("Релизы патча", false);
        patchPage.alertIsPresent("Тип патча", true);
        patchPage.alertIsPresent("Ветка формирования патча", false);
        patchPage.alertIsPresent("Проект реестра", false);

        //заполнение полей
        formPage.userSelectorSetValue("Ответственный", 1);
        formPage.userSelectorSetValue("Наблюдатели", 3);
        formPage.userSelectorSetValue("Владелец патча", 1);
        formPage.setDateValue("Плановая дата вывода из эксплуатации",
                DateUtils.getCurrentDate(0, "dd.MM.yyyy"));
        formPage.setRadioValue("Тип патча", 2);
        formPage.setListValue("Ветка формирования патча", 2);

        //проверяем наличие мультивыбора
        formPage.userSelectorIsMulti("Ответственный", false);
        formPage.userSelectorIsMulti("Наблюдатели", true);
        formPage.userSelectorIsMulti("Владелец патча", false);

        WaitManager.pause(5);

        //проверяем отсутствие валидации полей
        patchPage.alertIsPresent("Ответственный", false);
        patchPage.alertIsPresent("Наблюдатели", false);
        patchPage.alertIsPresent("Владелец патча", false);
        patchPage.alertIsPresent("Плановая дата вывода из эксплуатации", false);
        patchPage.alertIsPresent("Код клиента CSC", false);
        patchPage.alertIsPresent("Релизы патча", false);
        patchPage.alertIsPresent("Тип патча", false);
        patchPage.alertIsPresent("Ветка формирования патча", false);
        patchPage.alertIsPresent("Проект реестра", false);

    }

    @Test(enabled = false)
    public void formBySupportManager() {
        String user = "ibabushkin";

        auth(url, user);
        patchPage.setConfiguration()
                .openTaskForm();

        //ждем прорисовки варнингов
        WaitManager.pause(2);

        //проверяем количество отображаемых полей
        Assert.assertEquals(patchPage.presentFieldsCount(), 8);

        //проверяем наличие валидации полей
        patchPage.alertIsPresent("Ответственный", false);
        patchPage.alertIsPresent("Наблюдатели", false);
        patchPage.alertIsPresent("Владелец патча", true);
        patchPage.alertIsPresent("Плановая дата ввода в эксплуатацию", false);
        patchPage.alertIsPresent("Плановая дата завершения работы", false);
        patchPage.alertIsPresent("Релизы патча", false);
        patchPage.alertIsPresent("Тип патча", true);
        patchPage.alertIsPresent("Ветка формирования патча", false);

    }

    @Test(enabled = false)
    public void formByGroupTechnologyService() {
        String user = "vovsienko";

        auth(url, user);
        patchPage.setConfiguration()
                .openTaskForm();

        //ждем прорисовки варнингов
        WaitManager.pause(2);

        //проверяем количество отображаемых полей
        Assert.assertEquals(patchPage.presentFieldsCount(), 9);

        //проверяем наличие валидации полей
        patchPage.alertIsPresent("Ответственный", false);
        patchPage.alertIsPresent("Наблюдатели", false);
        patchPage.alertIsPresent("Владелец патча", true);
        patchPage.alertIsPresent("Плановая дата ввода в эксплуатацию", false);
        patchPage.alertIsPresent("Плановая дата завершения работы", false);
        patchPage.alertIsPresent("Код клиента CSC", false);
        patchPage.alertIsPresent("Релизы патча", false);
        patchPage.alertIsPresent("Тип патча", true);
        patchPage.alertIsPresent("Ветка формирования патча", false);

    }

    @Test(enabled = false)
    public void formByWorker() {
        String user = "aaskeev";

        auth(url, user);
        patchPage.setConfiguration()
                .openTaskForm();

        //ждем прорисовки варнингов
        WaitManager.pause(2);

        //проверяем количество отображаемых полей
        Assert.assertEquals(patchPage.presentFieldsCount(), 2);

        //проверяем наличие валидации полей
        patchPage.alertIsPresent("Ответственный", false);
        patchPage.alertIsPresent("Наблюдатели", false);

    }
}
