package com.ts.integration.tests.ui.tc1563098;

import com.codeborne.selenide.Selenide;
import com.ts.common.application.database.dbTables.GrTaskTable;
import com.ts.common.controllers.folder.SdPatchFolderController;
import com.ts.common.controllers.installation.InstallationController;
import com.ts.common.entitites.commonEntities.Parent;
import com.ts.common.entitites.commonEntities.Udfs;
import com.ts.common.entitites.tasks.GeneralTask;
import com.ts.common.ui.pages.FormPage;
import com.ts.common.ui.pages.LoginPage;
import com.ts.common.ui.pages.portlets.PatchPage;
import com.ts.common.utils.DateUtils;
import com.ts.common.utils.WaitManager;
import com.ts.integration.tests.BaseUiTest;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;


public class CreatePatchFormTest extends BaseUiTest {
    LoginPage loginPage;
    PatchPage patchPage;

    FormPage formPage;
    InstallationController installationController;
    SdPatchFolderController sdPatchFolderController;
    GeneralTask generalTask;
    Udfs udf;
    GrTaskTable grTaskTable;
    Parent parent;

    String url = "http://tsdev7.dev.colvir.ru/TrackStudio/app/portlet/patch?branch=AZPST";//TODO использовать ссылку через AppConfigProvider
    String admin = "root";
    String supportManager = "ibabushkin";
    String groupTechnologyService = "vovsienko";
    String worker = "aaskeev";

    @BeforeClass(alwaysRun = true)
    public void beforeClass() {
        loginPage = trackStudioPages.getLoginPage();
        patchPage = trackStudioPages.getPatchPage();
        formPage = trackStudioPages.getFormPage();

//        grTaskTable = dbHelper.getGrTaskTable();
//        GrTaskDbEntity grTaskDbEntity = (GrTaskDbEntity) grTaskTable.receiveByTaskName("AT_INSTALLATION");

//        //генерация структуры данных для тестов
//        installationController = apiController.getInstallationController();
//        sdPatchFolderController = apiController.getSdPatchfolderController();
//        //grTaskTable = dbHelper.getGrTaskTable();
//        //GrTaskDbEntity grTaskDbEntity = (GrTaskDbEntity) grTaskTable.receiveByTaskNumber("462311");
//
//        parent = InitEntities.generateParent("818180a050c582480150c947cb252eb5", "462311");
//        generalTask = InitEntities.getGeneralTask(BDKU_INSTALLATION, Operations.CAT);
//        udf = InitEntities.refreshUdf();
//        generalTask.setName("AT_INSTALLATION");
//        generalTask.setParent(parent);
//        udf.setUdfString(generateUdfString(UDF_BDKU_CSCCLIENT, "AT_INSTALLATION"));
//        generalTask.refreshUdf(udf);
//        installationController.createInstallation(generalTask);
//
//        parent = InitEntities.generateParent(generalTask.getId(), generalTask.getNumber());
//        generalTask = InitEntities.getGeneralTask(SDPATCHFOLDER, Operations.CAT);
//        udf = InitEntities.refreshUdf();
//        generalTask.setName("AT_SDPATCHFOLDER");
//        generalTask.setParent(parent);
//        //udf.setUdfString(generateUdfString(UDF_BDKU_CSCCLIENT, "AT_INSTALLATION"));
//        generalTask.refreshUdf(udf);
//        sdPatchFolderController.createSdPatchFolder(generalTask);
    }

    @AfterMethod
    public void afterTest() {
        Selenide.clearBrowserCookies();
    }

    @Test(enabled = true) //TODO добавить описание groups/description
    public void createByAdmin() {
        auth(url, admin);
        patchPage.setConfiguration()
                .openPatchForm();
        formPage.checkDraft();

        //ждем срабатывание варнингов
        WaitManager.pause(2);

        //проверяем количество отображаемых полей
        Assert.assertEquals(formPage.presentFieldsCount(), 9);//TODO тест падает на этом моменте

        //проверяем автогенерацию значений полей
        Assert.assertNotNull(patchPage.getAutoGeneratedName());
        Assert.assertNotNull(patchPage.getAutoGeneratedShortName());
        Assert.assertNotNull(patchPage.getAutoGeneratedBdkuCsclient());

        //проверяем наличие валидации полей
        formPage.alertIsPresent("Ответственный", false);
        formPage.alertIsPresent("Наблюдатели", false);
        formPage.alertIsPresent("Владелец патча", true);
        formPage.alertIsPresent("Плановая дата вывода из эксплуатации", false);
        formPage.alertIsPresent("Код клиента CSC", false);
        formPage.alertIsPresent("Релизы патча", false);
        formPage.alertIsPresent("Тип патча", true);
        formPage.alertIsPresent("Ветка формирования патча", false);
        formPage.alertIsPresent("Проект реестра", false);

        //заполняем поля
        formPage.userSelectorSetValue("Ответственный", 1);
        formPage.userSelectorSetValue("Наблюдатели", 3);
        formPage.userSelectorSetValue("Владелец патча", 1);
        formPage.setDateValue("Плановая дата вывода из эксплуатации",
                DateUtils.getCurrentDate(0, "dd.MM.yyyy"));
        formPage.setRadioValue("Тип патча", 2);
        formPage.setListValue("Ветка формирования патча", 2);

        //проверяем наличие мультивыбора
        formPage.userSelectorIsMulti("Ответственный", false);
        formPage.userSelectorIsMulti("Наблюдатели", true);
        formPage.userSelectorIsMulti("Владелец патча", false);

        //ждем срабатываение валидации
        WaitManager.pause(5);

        //проверяем отсутствие валидации полей
        formPage.alertIsPresent("Ответственный", false);
        formPage.alertIsPresent("Наблюдатели", false);
        formPage.alertIsPresent("Владелец патча", false);
        formPage.alertIsPresent("Плановая дата вывода из эксплуатации", false);
        formPage.alertIsPresent("Код клиента CSC", false);
        formPage.alertIsPresent("Релизы патча", false);
        formPage.alertIsPresent("Тип патча", false);
        formPage.alertIsPresent("Ветка формирования патча", false);
        formPage.alertIsPresent("Проект реестра", false);
    }

    @Test(enabled = true)//TODO добавить описание groups/description
    public void createBySupportManager() {
        auth(url, supportManager);
        patchPage.setConfiguration()
                .openPatchForm();
        formPage.checkDraft();

        //ждем срабатываение валидации
        WaitManager.pause(2);

        //проверяем количество отображаемых полей
        Assert.assertEquals(formPage.presentFieldsCount(), 8);//TODO тест падает на этом моменте

        //проверяем автогенерацию значений полей
        Assert.assertNotNull(patchPage.getAutoGeneratedName());
        Assert.assertNotNull(patchPage.getAutoGeneratedShortName());

        //проверяем наличие валидации полей
        formPage.alertIsPresent("Ответственный", false);
        formPage.alertIsPresent("Наблюдатели", false);
        formPage.alertIsPresent("Владелец патча", true);
        formPage.alertIsPresent("Плановая дата ввода в эксплуатацию", false);
        formPage.alertIsPresent("Плановая дата завершения работы", false);
        formPage.alertIsPresent("Релизы патча", false);
        formPage.alertIsPresent("Тип патча", true);
        formPage.alertIsPresent("Ветка формирования патча", false);

        //заполняем поля
        formPage.userSelectorSetValue("Ответственный", 1);
        formPage.userSelectorSetValue("Наблюдатели", 3);
        formPage.userSelectorSetValue("Владелец патча", 1);
        formPage.setDateValue("Плановая дата ввода в эксплуатаци",
                DateUtils.getCurrentDate(0, "dd.MM.yyyy"));
        formPage.setDateValue("Плановая дата завершения работы",
                DateUtils.getCurrentDate(0, "dd.MM.yyyy"));
        formPage.setRadioValue("Тип патча", 2);
        formPage.setListValue("Ветка формирования патча", 2);

        //проверяем наличие мультивыбора
        formPage.userSelectorIsMulti("Ответственный", false);
        formPage.userSelectorIsMulti("Наблюдатели", true);
        formPage.userSelectorIsMulti("Владелец патча", false);

        //ждем срабатываение валидации
        WaitManager.pause(5);

        //проверяем отсутствие валидации полей
        formPage.alertIsPresent("Ответственный", false);
        formPage.alertIsPresent("Наблюдатели", false);
        formPage.alertIsPresent("Владелец патча", false);
        formPage.alertIsPresent("Плановая дата ввода в эксплуатаци", false);
        formPage.alertIsPresent("Плановая дата завершения работы", false);
        formPage.alertIsPresent("Релизы патча", false);
        formPage.alertIsPresent("Тип патча", false);
        formPage.alertIsPresent("Ветка формирования патча", false);
    }

    @Test(enabled = true)//TODO добавить описание groups/description
    public void createByGroupTechnologyService() {
        auth(url, groupTechnologyService);
        patchPage.setConfiguration()
                .openPatchForm();
        WaitManager.pause(2);
        formPage.checkDraft();

        //ждем срабатывание варнингов
        WaitManager.pause(2);

        //проверяем количество отображаемых полей
        Assert.assertEquals(formPage.presentFieldsCount(), 9);//TODO тест падает на этом моменте

        //проверяем автогенерацию значений полей
        Assert.assertNotNull(patchPage.getAutoGeneratedName());
        Assert.assertNotNull(patchPage.getAutoGeneratedShortName());
        Assert.assertNotNull(patchPage.getAutoGeneratedBdkuCsclient());

        //проверяем наличие валидации полей
        formPage.alertIsPresent("Ответственный", false);
        formPage.alertIsPresent("Наблюдатели", false);
        formPage.alertIsPresent("Владелец патча", true);
        formPage.alertIsPresent("Плановая дата ввода в эксплуатацию", false);
        formPage.alertIsPresent("Плановая дата завершения работы", false);
        formPage.alertIsPresent("Код клиента CSC", false);
        formPage.alertIsPresent("Релизы патча", false);
        formPage.alertIsPresent("Тип патча", true);
        formPage.alertIsPresent("Ветка формирования патча", false);

        //заполняем поля
        formPage.userSelectorSetValue("Ответственный", 1);
        formPage.userSelectorSetValue("Наблюдатели", 3);
        formPage.userSelectorSetValue("Владелец патча", 1);
        formPage.setDateValue("Плановая дата ввода в эксплуатацию",
                DateUtils.getCurrentDate(0, "dd.MM.yyyy"));
        formPage.setDateValue("Плановая дата завершения работы",
                DateUtils.getCurrentDate(0, "dd.MM.yyyy"));
        formPage.setRadioValue("Тип патча", 2);
        formPage.setListValue("Ветка формирования патча", 2);

        //ждем срабатываение валидации
        WaitManager.pause(5);

        //проверяем отсутствие валидации полей
        formPage.alertIsPresent("Ответственный", false);
        formPage.alertIsPresent("Наблюдатели", false);
        formPage.alertIsPresent("Владелец патча", false);
        formPage.alertIsPresent("Плановая дата ввода в эксплуатацию", false);
        formPage.alertIsPresent("Плановая дата завершения работы", false);
        formPage.alertIsPresent("Код клиента CSC", false);
        formPage.alertIsPresent("Релизы патча", false);
        formPage.alertIsPresent("Тип патча", false);
        formPage.alertIsPresent("Ветка формирования патча", false);
    }

    @Test(enabled = true)//TODO добавить описание groups/description
    public void createByWorker() {
        auth(url, worker);
        patchPage.setConfiguration()
                .openPatchForm();
        formPage.checkDraft();

        //ждем срабатывание варнингов
        WaitManager.pause(2); //TODO добавить время валидации/варнингов как отдельную const в AppConfigProvider (желательно не использовать такое ожидание)

        //проверяем количество отображаемых полей
        Assert.assertEquals(formPage.presentFieldsCount(), 2);

        //проверяем автогенерацию значений полей
        Assert.assertNotNull(patchPage.getAutoGeneratedName());
        Assert.assertNotNull(patchPage.getAutoGeneratedShortName());

        //проверяем наличие валидации полей
        formPage.alertIsPresent("Ответственный", false);
        formPage.alertIsPresent("Наблюдатели", false);

        //заполняем поля
        formPage.userSelectorSetValue("Ответственный", 1);
        formPage.userSelectorSetValue("Наблюдатели", 3);

        //проверяем наличие мультивыбора
        formPage.userSelectorIsMulti("Ответственный", false);
        formPage.userSelectorIsMulti("Наблюдатели", true);

        //ждем срабатываение валидации
        WaitManager.pause(5); //TODO добавить время валидации/варнингов как отдельную const в AppConfigProvider (желательно не использовать такое ожидание)

        //проверяем отсутствие валидации полей
        formPage.alertIsPresent("Ответственный", false);
        formPage.alertIsPresent("Наблюдатели", false);
    }
}
