package com.ts.integration.tests.ui.tc1563098;

import com.codeborne.selenide.Selenide;
import com.ts.common.application.database.dbTables.GrTaskTable;
import com.ts.common.controllers.folder.SdPatchFolderController;
import com.ts.common.controllers.installation.InstallationController;
import com.ts.common.entitites.commonEntities.Parent;
import com.ts.common.entitites.commonEntities.Udfs;
import com.ts.common.entitites.tasks.GeneralTask;
import com.ts.common.ui.pages.LoginPage;
import com.ts.common.ui.pages.portlets.PatchPage;
import com.ts.common.utils.DateUtils;
import com.ts.common.utils.WaitManager;
import com.ts.integration.tests.BaseUiTest;
import org.testng.Assert;
import org.testng.annotations.*;

import static com.codeborne.selenide.Selenide.open;
import static com.ts.common.utils.InitEntities.generateUdfString;


public class EditPatchFormTest extends BaseUiTest {
    LoginPage loginPage;
    PatchPage patchPage;
    InstallationController installationController;
    SdPatchFolderController sdPatchFolderController;
    GeneralTask generalTask;
    Udfs udf;
    GrTaskTable grTaskTable;
    Parent parent;

    String url = "http://tsdev7.dev.colvir.ru/TrackStudio/app/portlet/patch?branch=AZPST";
    String admin = "root";
    String supportManager = "ibabushkin";
    String groupTechnologyService = "vovsienko";
    String worker = "aaskeev";

    @BeforeClass(alwaysRun = true)
    public void beforeClass() {
        loginPage = trackStudioPages.getLoginPage();
        patchPage = trackStudioPages.getPatchPage();

//        grTaskTable = dbHelper.getGrTaskTable();
//        GrTaskDbEntity grTaskDbEntity = (GrTaskDbEntity) grTaskTable.receiveByTaskName("AT_INSTALLATION");

//        //генерация структуры данных для тестов
//        installationController = apiController.getInstallationController();
//        sdPatchFolderController = apiController.getSdPatchfolderController();
//        //grTaskTable = dbHelper.getGrTaskTable();
//        //GrTaskDbEntity grTaskDbEntity = (GrTaskDbEntity) grTaskTable.receiveByTaskNumber("462311");
//
//        parent = InitEntities.generateParent("818180a050c582480150c947cb252eb5", "462311");
//        generalTask = InitEntities.getGeneralTask(BDKU_INSTALLATION, Operations.CAT);
//        udf = InitEntities.refreshUdf();
//        generalTask.setName("AT_INSTALLATION");
//        generalTask.setParent(parent);
//        udf.setUdfString(generateUdfString(UDF_BDKU_CSCCLIENT, "AT_INSTALLATION"));
//        generalTask.refreshUdf(udf);
//        installationController.createInstallation(generalTask);
//
//        parent = InitEntities.generateParent(generalTask.getId(), generalTask.getNumber());
//        generalTask = InitEntities.getGeneralTask(SDPATCHFOLDER, Operations.CAT);
//        udf = InitEntities.refreshUdf();
//        generalTask.setName("AT_SDPATCHFOLDER");
//        generalTask.setParent(parent);
//        //udf.setUdfString(generateUdfString(UDF_BDKU_CSCCLIENT, "AT_INSTALLATION"));
//        generalTask.refreshUdf(udf);
//        sdPatchFolderController.createSdPatchFolder(generalTask);
    }

    @AfterMethod
    public void afterTest() {
        Selenide.clearBrowserCookies();
    }
    @Test(enabled = true)
    public void editeByAdmin() {
        auth(url, admin);
        patchPage.setConfiguration()
                .openPatchForm();

        String taskName = patchPage.getAutoGeneratedName();

        formPage.checkDraft();

        //заполняем поля и сохраняем форму
        formPage.userSelectorSetValue("Ответственный", 1);
        formPage.userSelectorSetValue("Наблюдатели", 3);
        formPage.userSelectorSetValue("Владелец патча", 1);
        formPage.setDateValue("Плановая дата вывода из эксплуатации",
                DateUtils.getCurrentDate(0, "dd.MM.yyyy"));
        formPage.setRadioValue("Тип патча", 2);
        formPage.setListValue("Ветка формирования патча", 2);
        formPage.clickButton("Создать и перейти к задаче");

        //проверяем что задача создана
        formPage.checkCurrentTask(taskName);

        //проверяем список полей
        formPage.setMenuOption("Управление задачей", "Редактировать");
        formPage.fieldIsPresent("Ответственный", false);
        formPage.fieldIsPresent("Наблюдатели", true);
        formPage.fieldIsPresent("Владелец патча", true);
        formPage.fieldIsPresent("Плановая дата ввода в эксплуатацию", false);
        formPage.fieldIsPresent("Плановая дата завершения работы", false);
        formPage.fieldIsPresent("Плановая дата вывода из эксплуатации", true);
        formPage.fieldIsPresent("Плановая дата кодефриза", false);
        formPage.fieldIsPresent("Плановая дата начала программирования", false);
        formPage.fieldIsPresent("Плановая дата фичефриза", false);
        formPage.fieldIsPresent("Код клиента CSC", true);
        formPage.fieldIsPresent("Релизы патча", true);
        formPage.fieldIsPresent("Тип патча", true);
        formPage.fieldIsPresent("Ветка формирования патча", true);
        formPage.fieldIsPresent("Проект реестра", true);
        formPage.fieldIsPresent("Связанные задачи", true);
    }

    @Test(enabled = true)
    public void editBySupportManager() {
        auth(url, supportManager);
        patchPage.setConfiguration()
                .openPatchForm();

        String taskName = patchPage.getAutoGeneratedName();

        formPage.checkDraft();

        //заполняем поля и сохраняем форму
        formPage.userSelectorSetValue("Ответственный", 1);
        formPage.userSelectorSetValue("Наблюдатели", 3);
        formPage.userSelectorSetValue("Владелец патча", 1);
        formPage.setDateValue("Плановая дата ввода в эксплуатаци",
                DateUtils.getCurrentDate(0, "dd.MM.yyyy"));
        formPage.setDateValue("Плановая дата завершения работы",
                DateUtils.getCurrentDate(0, "dd.MM.yyyy"));
        formPage.setRadioValue("Тип патча", 2);
        formPage.setListValue("Ветка формирования патча", 2);
        formPage.clickButton("Создать и перейти к задаче");

        //проверяем что задача создана
        formPage.checkCurrentTask(taskName);

        //проверяем список полей
        formPage.setMenuOption("Управление задачей", "Редактировать");
        formPage.fieldIsPresent("Ответственный", false);
        formPage.fieldIsPresent("Наблюдатели", true);
        formPage.fieldIsPresent("Владелец патча", false);
        formPage.fieldIsPresent("Плановая дата ввода в эксплуатацию", true);
        formPage.fieldIsPresent("Плановая дата завершения работы", true);
        formPage.fieldIsPresent("Плановая дата вывода из эксплуатации", false);
        formPage.fieldIsPresent("Плановая дата кодефриза", false);
        formPage.fieldIsPresent("Плановая дата начала программирования", false);
        formPage.fieldIsPresent("Плановая дата фичефриза", false);
        formPage.fieldIsPresent("Код клиента CSC", false);
        formPage.fieldIsPresent("Релизы патча", true);
        formPage.fieldIsPresent("Тип патча", true);
        formPage.fieldIsPresent("Ветка формирования патча", true);
        formPage.fieldIsPresent("Проект реестра", false);
        formPage.fieldIsPresent("Связанные задачи", true);
    }

    @Test(enabled = true)
    public void editByGroupTechnologyService() {
        auth(url, groupTechnologyService);
        patchPage.setConfiguration()
                .openPatchForm();

        String taskName = patchPage.getAutoGeneratedName();

        formPage.checkDraft();

        //заполняем поля и сохраняем форму
        formPage.userSelectorSetValue("Ответственный", 1);
        formPage.userSelectorSetValue("Наблюдатели", 3);
        formPage.userSelectorSetValue("Владелец патча", 1);
        formPage.setDateValue("Плановая дата ввода в эксплуатацию",
                DateUtils.getCurrentDate(0, "dd.MM.yyyy"));
        formPage.setDateValue("Плановая дата завершения работы",
                DateUtils.getCurrentDate(0, "dd.MM.yyyy"));
        formPage.setRadioValue("Тип патча", 2);
        formPage.setListValue("Ветка формирования патча", 2);
        formPage.clickButton("Создать и перейти к задаче");

        //проверяем что задача создана
        formPage.checkCurrentTask(taskName);

        //проверяем список полей
        formPage.setMenuOption("Управление задачей", "Редактировать");
        formPage.fieldIsPresent("Ответственный", false);
        formPage.fieldIsPresent("Наблюдатели", true);
        formPage.fieldIsPresent("Владелец патча", false);
        formPage.fieldIsPresent("Плановая дата ввода в эксплуатацию", true);
        formPage.fieldIsPresent("Плановая дата завершения работы", true);
        formPage.fieldIsPresent("Плановая дата вывода из эксплуатации", false);
        formPage.fieldIsPresent("Плановая дата кодефриза", false);
        formPage.fieldIsPresent("Плановая дата начала программирования", false);
        formPage.fieldIsPresent("Плановая дата фичефриза", false);
        formPage.fieldIsPresent("Код клиента CSC", true);
        formPage.fieldIsPresent("Релизы патча", true);
        formPage.fieldIsPresent("Тип патча", true);
        formPage.fieldIsPresent("Ветка формирования патча", true);
        formPage.fieldIsPresent("Проект реестра", false);
        formPage.fieldIsPresent("Связанные задачи", true);
    }
}
